
# 自动刷新
live_config_reload: true
# Tab 缩进
tabspaces: 4
# 背景透明度
window.opacity: 0.9

shell:
  program: /bin/zsh
  # windows
  # program: c:\windows\system32\windowspowershell\v1.0\powershell.exe
  args:
    # login
    - -l
    # - -c
    # - 'zellij --layout ~/.config/zellij/config.yaml attach --index 0 --create'

window:
  # 窗口大小
  dimensions:
    columns: 120
    lines: 60

  # 边缘空白
  padding:
    x: 16
    y: 16
  dynamic_padding: false
  startup_mode: Maximized
  # 窗口修饰
  # - full: 有边界+标题栏
  # - none: 无边界+标题栏
  decorations: none

scrolling:
  # 历史保留行数
  history: 2000

  # 每次滚动行数
  multiplier: 5

  # 每次滚动行数（分屏时）
  faux_multiplier: 100

  # 自动滚动至最新行
  auto_scroll: true

font:
  size: 16
  # 字体
  # CaskaydiaCove Nerd Font
  normal:
    family: 'CaskaydiaCove Nerd Font'
    style: Regular
  bold:
    family: 'CaskaydiaCove Nerd Font'
    style: Bold
  italic:
    family: 'CaskaydiaCove Nerd Font'
    style: Italic
  bold_{i}talic:
    family: 'CaskaydiaCove Nerd Font'
    style: Bold Italic

  # 细描边
  # use_thin_strokes: true
cursor:
  style:
    shape: Beam

# Colors (iTerm 2 default theme)
colors:
  # Default colors
  primary:
    background: '#282c34'
    foreground: '#abb2bf'

  # Normal colors
  normal:
    black:   '#282c34'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

  # Bright colors
  bright:
    black:   '#5c6370'
    red:     '#d19a66'
    green:   '#56b6c2'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'
