general.live_config_reload = true
general.import = ["/Users/zhangyongqi/.local/share/nvim/lazy/tokyonight.nvim/extras/alacritty/tokyonight_storm.toml"]

[colors]
draw_bold_text_with_bright_colors = true

# [colors.bright]
# black = "#5c6370"
# blue = "#61afef"
# cyan = "#56b6c2"
# green = "#56b6c2"
# magenta = "#c678dd"
# red = "#d19a66"
# white = "#abb2bf"
# yellow = "#e5c07b"
#
# [colors.normal]
# black = "#282c34"
# blue = "#61afef"
# cyan = "#56b6c2"
# green = "#98c379"
# magenta = "#c678dd"
# red = "#e06c75"
# white = "#abb2bf"
# yellow = "#e5c07b"
#
# [colors.primary]
# background = "#282c34"
# foreground = "#abb2bf"

[cursor.style]
shape = "Beam"

[font]
size = 16

[font.bold]
family = "FiraCode Nerd Font"

[font.bold_italic]
family = "VictorMono Nerd Font"

[font.italic]
family = "VictorMono Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"

[scrolling]
history = 2000
multiplier = 5

[terminal.shell]
args = ["-l"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = false
startup_mode = "Maximized"

[window.dimensions]
columns = 120
lines = 60

[window.padding]
x = 16
y = 16
