
default_shell: zsh
on_force_close: detach

simplified_ui: false
pane_frames: false
theme: default

default_mode: normal
mouse_mode: true
scroll_buffer_size: 10000

# template:
#   direction: Horizontal
#   parts:
#     - direction: Vertical
#       borderless: true
#       split_size:
#         Fixed: 1
#       run:
#         plugin:
#           location: 'zellij:tab-bar'
#     - direction: Vertical
#       body: true
#     - direction: Vertical
#       borderless: true
#       split_size:
#         Fixed: 2
#       run:
#         plugin:
#           location: 'zellij:status-bar'

# tabs:
#   - name: 'Tab 1'
#     direction: Horizontal
#     parts:
#       - direction: Vertical
#         split_size:
#           Percent: 60
#       - direction: Vertical
#         parts:
#           - direction: Horizontal
#           - direction: Horizontal
